NDefines.NMilitary.BASE_MP_TO_MANPOWER = 0.175	-- Reduced to 175 for Balance purposes
NDefines.NCountry.MIGRATORY_TRIBE_DEVELOPMENT_OTHER_BONUS = 0.03	-- Bonus progress gained on development from burning someone else province.
NDefines.NCountry.MIGRATORY_TRIBE_DEVELOPMENT_PROGRESS = 0.01 	-- How much progress on development for each monthly tick
NDefines.NDiplomacy.IMPERIAL_AUTHORITY_FROM_PRINCES = 0.062


-- Inspired by Xorme's AI. Implemented so the AI can substain Estate Policies
NDefines.NAI.ESTATE_MAX_PRIVILEDGES = 4
NDefines.NAI.ESTATE_MAX_WANTED_INFLUENCE = 87.0
NDefines.NAI.ESTATE_MIN_WANTED_CROWNLAND = 30.0
NDefines.NAI.DANGEROUS_ESTATE_INFLUENCE_BUFFER = 6.5


NDefines.NCountry.BASE_POSSIBLE_POLICIES = 2
NDefines.NCountry.MAX_ACTIVE_POLICIES = 6

-- New 1.33 Change
NDefines.NDiplomacy.PEACE_COST_TAKE_MANDATE = 30

NDefines.NCountry.COHESION_FEDERATION_MEMBER_WRONG_CULTURE = 0.05
NDefines.NCountry.COHESION_FEDERATION_MEMBER_CORRECT_CULTURE = 0.10
NDefines.NCountry.COHESION_FEDERATION_MEMBER_STRONGER = -0.20
NDefines.NCountry.COHESION_FEDERATION_MEMBER_STRONGER_WRONG_CULTURE = -0.40
NDefines.NCountry.COHESION_FEDERATION_SAME_CULTURE_MEMBERS_BONUS_NUMBER = 2
NDefines.NCountry.COHESION_FEDERATION_SAME_CULTURE_MEMBERS_BONUS_MODIFIER = 0.25
NDefines.NCountry.COHESION_NEIGHBOURING_COLONIZER = 0.25
NDefines.NCountry.COHESION_FEDERATION_ADVANCEMENT = -0.05
NDefines.NCountry.FEDERATION_DESIRABILITY_WRONG_CULTURE_GROUP = -100
NDefines.NCountry.FEDERATION_DESIRABILITY_SAME_CULTURE = 100
NDefines.NCountry.FEDERATION_DESIRABILITY_SAME_CULTURE_GROUP = -20
NDefines.NCountry.FEDERATION_DESIRABILITY_LAND_BALANCE_MULTIPLIER = 20
NDefines.NCountry.FEDERATION_DESIRABILITY_STRONGER_THAN_LEADER_MALUS = -100
NDefines.NCountry.FEDERATION_DESIRABILITY_WANTS_ALLY = 20
NDefines.NCountry.FEDERATION_DESIRABILITY_WANTS_BEFRIEND = 20
NDefines.NCountry.FEDERATION_DESIRABILITY_WANTS_ANTAGONIZE = -40
NDefines.NCountry.FEDERATION_DESIRABILITY_WANTS_WEAKEN = -10
NDefines.NCountry.FEDERATION_DESIRABILITY_DONT_WANT_TO_CHANGE = -30
NDefines.NCountry.FEDERATION_ACTION_COOLDOWN = 15

NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.49

NDefines.NMilitary.SCORCHED_DEVASTATION_IMPACT = 15
NDefines.NCountry.PS_SCORCH_EARTH = 10
NDefines.NCountry.PS_PROMOTE_MERCANTILISM = 50
NDefines.NDiplomacy.GREAT_PROJECT_WARSCORE_COST_MODIFIER = 0.15
-- New 1.34 Changes
NDefines.NMilitary.CAVALRY_COST = 20.0
NDefines.NMilitary.ARTILLERY_COST = 32.0